# Generated by Django 5.1.3 on 2024-11-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='managed_buildings',
            new_name='buildings',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='guarded_entrances',
            new_name='entrances',
        ),
    ]
